### PR TITLE
Updated the unified branch

### PR DESCRIPTION
**Pull request by GieltjE**

### CODE REVIEW

**Comment by captainhook** [comment]
Do you want to include anything from #182?

**Comment by GieltjE** [comment]
> Do you want to include anything from #182?

Definately, the licensing should be the same internaly so that part should be kept up to date.
Thanks for the heads up.

**Comment by GieltjE** [comment]
Up to date now, really hope they start shipping the unified version sometime

**Comment by captainhook** [comment]
Thanks @GieltjE

**Pull request merged**
